Repository sxxcxng/OSS_teamG, pull requests merged in 2024-06, with the labels that each got.

#27 Feature/IncreasedMissileItem#25
  PyShooting.py
  __pycache__/game_objects.cpython-311.pyc
  __pycache__/resources.cpython-311.pyc
  clear_item.png
  empty_heart.png
  full_heart.png
  missile_item.png
  pyshooting/__init__.py
  pyshooting/__pycache__/__init__.cpython-311.pyc
  pyshooting/__pycache__/__init__.cpython-312.pyc
  pyshooting/__pycache__/audio.cpython-311.pyc
  pyshooting/__pycache__/audio.cpython-312.pyc
  pyshooting/__pycache__/game.cpython-311.pyc
  pyshooting/__pycache__/game.cpython-312.pyc
  pyshooting/__pycache__/graphics.cpython-311.pyc
  pyshooting/__pycache__/graphics.cpython-312.pyc
  pyshooting/__pycache__/main.cpython-311.pyc
  pyshooting/__pycache__/main.cpython-312.pyc
  pyshooting/__pycache__/messages.cpython-311.pyc
  pyshooting/__pycache__/messages.cpython-312.pyc
  pyshooting/__pycache__/resources.cpython-311.pyc
  pyshooting/__pycache__/resources.cpython-312.pyc
  pyshooting/__pycache__/settingTab.cpython-311.pyc
  pyshooting/__pycache__/settingTab.cpython-312.pyc
  pyshooting/audio.py
  pyshooting/game.py
  pyshooting/graphics.py
  pyshooting/main.py
  pyshooting/messages.py
  pyshooting/resources.py
  pyshooting/settingTab.py
  rungame.py
Labels: 🙆🏻‍♀️ 구현 완료, ✨기능 추가

#29 Feature/IncreasedMissileItem#25
  missile_item.png
  pyshooting/__pycache__/__init__.cpython-312.pyc
  pyshooting/__pycache__/audio.cpython-312.pyc
  pyshooting/__pycache__/game.cpython-312.pyc
  pyshooting/__pycache__/graphics.cpython-312.pyc
  pyshooting/__pycache__/messages.cpython-312.pyc
  pyshooting/__pycache__/resources.cpython-312.pyc
  pyshooting/__pycache__/settingTab.cpython-312.pyc
  pyshooting/game.py
  pyshooting/main.py
Labels: 🙆🏻‍♀️ 구현 완료, ✨기능 추가

#33 Feat/AddFeature#26
  pyshooting/game.py
Labels: 🙆🏻‍♀️ 구현 완료, ✨기능 추가, 🙏 PR 중..

#35 Feat/CleanCode#34
  pyshooting/audio.py
  pyshooting/game.py
  pyshooting/resources.py
Labels: 🙏 PR 중.., ♻️ 클린 코드 개선

#37 Refactor/MakeRockClass#36
  pyshooting/__pycache__/audio.cpython-312.pyc
  pyshooting/__pycache__/game.cpython-312.pyc
  pyshooting/__pycache__/main.cpython-312.pyc
  pyshooting/__pycache__/resources.cpython-312.pyc
  pyshooting/__pycache__/settingTab.cpython-312.pyc
Labels: 🙏 PR 중.., ♻️ 클린 코드 개선

#39 Refactor/MakeRockClass#36
  pyshooting/game.py
Labels: 🙏 PR 중.., ♻️ 클린 코드 개선

#38 Refactor/pause#21
  pyshooting/game.py
Labels: 🙆🏻‍♀️ 구현 완료, ♻️ 클린 코드 개선

#43 Refactor/SimplifiedCodeLogic#41
  pyshooting/__pycache__/__init__.cpython-312.pyc
  pyshooting/__pycache__/audio.cpython-312.pyc
  pyshooting/__pycache__/game.cpython-312.pyc
  pyshooting/__pycache__/graphics.cpython-312.pyc
  pyshooting/__pycache__/main.cpython-312.pyc
  pyshooting/__pycache__/messages.cpython-312.pyc
  pyshooting/__pycache__/resources.cpython-312.pyc
  pyshooting/__pycache__/settingTab.cpython-312.pyc
  pyshooting/game.py
Labels: 🙆🏻‍♀️ 구현 완료, ♻️ 클린 코드 개선

#46 Feat/ ControlFighterJetPosition#30
  pyshooting/game.py
Labels: 🙆🏻‍♀️ 구현 완료, ✨기능 추가

#47 Feat/ChangeRockExplosion#30
  pyshooting/__pycache__/__init__.cpython-312.pyc
  pyshooting/__pycache__/audio.cpython-312.pyc
  pyshooting/__pycache__/game.cpython-312.pyc
  pyshooting/__pycache__/graphics.cpython-312.pyc
  pyshooting/__pycache__/main.cpython-312.pyc
  pyshooting/__pycache__/messages.cpython-312.pyc
  pyshooting/__pycache__/resources.cpython-312.pyc
  pyshooting/__pycache__/settingTab.cpython-312.pyc
  pyshooting/game.py
  pyshooting/graphics.py
Labels: 🙆🏻‍♀️ 구현 완료, ✨기능 추가

#48 Refactor/FunctionsVariablesOptimization#42
  pyshooting/audio.py
  pyshooting/game.py
  pyshooting/graphics.py
  pyshooting/main.py
  pyshooting/messages.py
  pyshooting/resources.py
Labels: 🙏 PR 중.., ♻️ 클린 코드 개선

#50 RefactorCleanCode#49
  pyshooting/audio.py
  pyshooting/game.py
  pyshooting/graphics.py
  pyshooting/main.py
  pyshooting/messages.py
  pyshooting/resources.py
  pyshooting/settingTab.py
Labels: 🙆🏻‍♀️ 구현 완료, ♻️ 클린 코드 개선
